version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dblicenses
      - POSTGRES_USER=licenses
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/license_portal
    ports:
      - "8000:8000"
    depends_on:
      - db